apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ./logging/
    repoURL: 'https://github.com/gelo22/cluster-dev'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

