apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ./
    repoURL: 'https://github.com/shalb/cluster.dev-monitoring'
    targetRevision: chart_rename
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
