image: docker:19.03.0

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  CLUSTER_DEV_BRANCH: "master"
  CLUSTER_CONFIG_PATH: "./.cluster.dev/"
  DIGITALOCEAN_TOKEN: "${DIGITALOCEAN_TOKEN}"
  SPACES_ACCESS_KEY_ID: "${SPACES_ACCESS_KEY_ID}"
  SPACES_SECRET_ACCESS_KEY: "${SPACES_SECRET_ACCESS_KEY}"

services:
  - docker:19.03.0-dind

before_script:
  - apk update && apk upgrade && apk add --no-cache bash git

stages:
  - cluster-dev

cluster-dev:
  only:
    refs:
      - master
    changes:
      - '.gitlab-ci.yml'
      - '.cluster.dev/**' # Path to cluster declaration manifests
      - '/kubernetes/apps/**' # ArgoCD application directories
  script:
    - git clone -b "$CLUSTER_DEV_BRANCH" https://github.com/shalb/cluster.dev.git
    - cd cluster.dev && docker build --no-cache -t "cluster.dev" .
    - docker run --name cluster.dev --workdir /gitlab/workspace --rm -e CI_PROJECT_PATH -e CI_PROJECT_DIR -e VERBOSE_LVL=DEBUG -e DIGITALOCEAN_TOKEN -e SPACES_ACCESS_KEY_ID -e SPACES_SECRET_ACCESS_KEY -v "${CI_PROJECT_DIR}:/gitlab/workspace" cluster.dev
  stage: cluster-dev
