apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: monitoring/prometheus-operator-customized/
    repoURL: 'https://github.com/gelo22/cluster-dev-gelo-test'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

